.PHONY: setup deploy-base-dev deploy-base-prod \
        build-amazon deploy-amazon-dev deploy-amazon-prod test-amazon \
        deploy-amazon-secrets-prod \
        build-rotation \
        deploy-rotation-services-dev deploy-rotation-bobnathan-dev \
        deploy-rotation-services-prod

# ---- Bootstrap ----
setup:
	uv sync --frozen --all-packages

# ---- Base stack (cross-platform shared resources) ----
deploy-base-dev:
	sam deploy --template infrastructure/base-stack.yaml \
		--stack-name sincerelyhers-base-dev \
		--profile sincerelyhers-dev \
		--region us-east-2 \
		--parameter-overrides Environment=dev \
		--capabilities CAPABILITY_IAM

deploy-base-prod:
	@test -n "$$PROD_ACCOUNT_ID" || (echo "ERROR: PROD_ACCOUNT_ID not set. 'source .identifiers.local' (or export it manually) and retry." && exit 1)
	@echo ""
	@echo "WARNING: About to deploy BASE stack to PROD (account $$PROD_ACCOUNT_ID)."
	@echo "  Stack:   sincerelyhers-base-prod"
	@echo "  Profile: sincerelyhers-prod"
	@echo "  Role:    arn:aws:iam::$$PROD_ACCOUNT_ID:role/DeploymentRole"
	@echo ""
	@bash -c 'read -p "Type '\''deploy prod'\'' to continue: " confirm && [ "$$confirm" = "deploy prod" ] || (echo "Aborted." && exit 1)'
	sam deploy --template infrastructure/base-stack.yaml \
		--stack-name sincerelyhers-base-prod \
		--profile sincerelyhers-prod \
		--role-arn arn:aws:iam::$$PROD_ACCOUNT_ID:role/DeploymentRole \
		--region us-east-2 \
		--parameter-overrides Environment=prod \
		--capabilities CAPABILITY_IAM

# ---- Amazon platform stack ----
build-amazon:
	uv export --frozen --no-dev --no-emit-workspace --package sincerelyhers-amazon \
		--output-file platforms/amazon/src/requirements.txt
	sam build --template platforms/amazon/template.yaml --use-container

deploy-amazon-dev: build-amazon
	sam deploy --template .aws-sam/build/template.yaml \
		--stack-name sincerelyhers-amazon-dev \
		--profile sincerelyhers-dev \
		--region us-east-2 \
		--parameter-overrides Environment=dev BaseStackName=sincerelyhers-base-dev \
		--capabilities CAPABILITY_NAMED_IAM \
		--resolve-s3

deploy-amazon-prod: build-amazon
	@test -n "$$PROD_ACCOUNT_ID" || (echo "ERROR: PROD_ACCOUNT_ID not set. 'source .identifiers.local' (or export it manually) and retry." && exit 1)
	@echo ""
	@echo "WARNING: About to deploy to PROD (account $$PROD_ACCOUNT_ID)."
	@echo "  Stack:   sincerelyhers-amazon-prod"
	@echo "  Profile: sincerelyhers-prod"
	@echo "  Role:    arn:aws:iam::$$PROD_ACCOUNT_ID:role/DeploymentRole"
	@echo ""
	@bash -c 'read -p "Type '\''deploy prod'\'' to continue: " confirm && [ "$$confirm" = "deploy prod" ] || (echo "Aborted." && exit 1)'
	sam deploy --template .aws-sam/build/template.yaml \
		--stack-name sincerelyhers-amazon-prod \
		--profile sincerelyhers-prod \
		--role-arn arn:aws:iam::$$PROD_ACCOUNT_ID:role/DeploymentRole \
		--region us-east-2 \
		--parameter-overrides Environment=prod BaseStackName=sincerelyhers-base-prod \
		--capabilities CAPABILITY_NAMED_IAM \
		--s3-bucket sincerelyhers-deploy-artifacts-prod \
		--s3-prefix amazon

# Prod SP-API secrets: app + per-seller credentials AND per-seller Odoo
# webhook config. Pure CloudFormation, no build step. Deployed via
# `aws cloudformation deploy --parameter-overrides file://` (NOT sam deploy)
# because samcli's parameter parser corrupts JSON values; the params file is
# generated by scripts/build_cfn_params.py and removed afterward. Deployed
# rarely; see docs/handoffs/amazon-prod-cutover.md. Dev secrets are
# CLI-created, so there is intentionally no -dev counterpart.
deploy-amazon-secrets-prod:
	@test -n "$$PROD_ACCOUNT_ID" || (echo "ERROR: PROD_ACCOUNT_ID not set. 'source .identifiers.local' (or export it manually) and retry." && exit 1)
	@test -f secrets/app-credentials.json || (echo "ERROR: secrets/app-credentials.json missing — stage {client_id, client_secret} before deploying." && exit 1)
	@for a in kk llg co 73j oh sh; do test -f secrets/credentials-$$a.json || (echo "ERROR: secrets/credentials-$$a.json missing — stage {refresh_token} before deploying." && exit 1); done
	@for a in kk llg co; do test -f secrets/amazon-feed-$$a.json || (echo "ERROR: secrets/amazon-feed-$$a.json missing — stage {secret, url, seller_id} before deploying." && exit 1); done
	@for a in kk llg co 73j oh sh; do test -f secrets/amazon-datakiosk-$$a.json || (echo "ERROR: secrets/amazon-datakiosk-$$a.json missing — stage {secret, url, account_id} before deploying." && exit 1); done
	@echo ""
	@echo "WARNING: About to deploy SP-API secrets to PROD (account $$PROD_ACCOUNT_ID)."
	@echo "  Stack:   sincerelyhers-amazon-secrets-prod"
	@echo "  Role:    arn:aws:iam::$$PROD_ACCOUNT_ID:role/DeploymentRole"
	@echo ""
	@echo "Deployed rarely (bootstrap / re-key / re-auth / webhook rotation). Once the"
	@echo "  prod rotation pipeline is live, do NOT redeploy without the CURRENT"
	@echo "  app/credentials value or it will clobber the rotated secret."
	@echo ""
	@bash -c 'read -p "Type '\''deploy prod'\'' to continue: " confirm && [ "$$confirm" = "deploy prod" ] || (echo "Aborted." && exit 1)'
	python3 scripts/build_cfn_params.py \
		SecretsPrefix=sp-api/sincerely-services \
		AppCredentialsJson=@secrets/app-credentials.json \
		KKCredentialsJson=@secrets/credentials-kk.json \
		LLGCredentialsJson=@secrets/credentials-llg.json \
		COCredentialsJson=@secrets/credentials-co.json \
		KKWebhookJson=@secrets/amazon-feed-kk.json \
		LLGWebhookJson=@secrets/amazon-feed-llg.json \
		COWebhookJson=@secrets/amazon-feed-co.json \
		73JCredentialsJson=@secrets/credentials-73j.json \
		OHCredentialsJson=@secrets/credentials-oh.json \
		SHCredentialsJson=@secrets/credentials-sh.json \
		KKDataKioskJson=@secrets/amazon-datakiosk-kk.json \
		LLGDataKioskJson=@secrets/amazon-datakiosk-llg.json \
		CODataKioskJson=@secrets/amazon-datakiosk-co.json \
		73JDataKioskJson=@secrets/amazon-datakiosk-73j.json \
		OHDataKioskJson=@secrets/amazon-datakiosk-oh.json \
		SHDataKioskJson=@secrets/amazon-datakiosk-sh.json \
		> secrets/.cfn-params-secrets.json
	aws cloudformation deploy --template-file platforms/amazon/secrets-template.yaml \
		--stack-name sincerelyhers-amazon-secrets-prod \
		--profile sincerelyhers-prod \
		--role-arn arn:aws:iam::$$PROD_ACCOUNT_ID:role/DeploymentRole \
		--region us-east-2 \
		--parameter-overrides file://secrets/.cfn-params-secrets.json \
		--no-fail-on-empty-changeset; \
		status=$$?; rm -f secrets/.cfn-params-secrets.json; exit $$status

test-amazon:
	uv run pytest platforms/amazon/tests/ -v

# ---- Amazon rotation pipeline (per-app stack, deployed once per SPP app) ----
# Build artifacts go to .aws-sam/rotation-build to coexist with the main
# amazon stack's .aws-sam/build (sam defaults to /build, so we override).
build-rotation:
	uv export --frozen --no-dev --no-emit-workspace --package sincerelyhers-amazon \
		--output-file platforms/amazon/src/requirements.txt
	sam build --template platforms/amazon/rotation-template.yaml \
		--build-dir .aws-sam/rotation-build --use-container

deploy-rotation-services-dev: build-rotation
	sam deploy --template .aws-sam/rotation-build/template.yaml \
		--stack-name sincerelyhers-amazon-rotation-services-dev \
		--profile sincerelyhers-dev \
		--region us-east-2 \
		--parameter-overrides Environment=dev AppShortName=services SecretsPrefix=sp-api/sincerely-services BaseStackName=sincerelyhers-base-dev \
		--capabilities CAPABILITY_NAMED_IAM \
		--resolve-s3

deploy-rotation-bobnathan-dev: build-rotation
	sam deploy --template .aws-sam/rotation-build/template.yaml \
		--stack-name sincerelyhers-amazon-rotation-bobnathan-dev \
		--profile sincerelyhers-dev \
		--region us-east-2 \
		--parameter-overrides Environment=dev AppShortName=bobnathan SecretsPrefix=sp-api/bobnathan-test BaseStackName=sincerelyhers-base-dev \
		--capabilities CAPABILITY_NAMED_IAM \
		--resolve-s3

deploy-rotation-services-prod: build-rotation
	@test -n "$$PROD_ACCOUNT_ID" || (echo "ERROR: PROD_ACCOUNT_ID not set. 'source .identifiers.local' (or export it manually) and retry." && exit 1)
	@echo ""
	@echo "WARNING: About to deploy ROTATION pipeline (Sincerely Services) to PROD (account $$PROD_ACCOUNT_ID)."
	@echo "  Stack:   sincerelyhers-amazon-rotation-services-prod"
	@echo "  Role:    arn:aws:iam::$$PROD_ACCOUNT_ID:role/DeploymentRole"
	@echo ""
	@echo "Precondition: ProtectProductionSecrets SCP must be amended (D1) to allow"
	@echo "  PutSecretValue on app/credentials by CredentialRotationProcessorRole."
	@echo "  This stack will deploy regardless, but the processor Lambda will fail"
	@echo "  on PutSecretValue at runtime until the SCP carve-out lands."
	@echo ""
	@bash -c 'read -p "Type '\''deploy prod'\'' to continue: " confirm && [ "$$confirm" = "deploy prod" ] || (echo "Aborted." && exit 1)'
	sam deploy --template .aws-sam/rotation-build/template.yaml \
		--stack-name sincerelyhers-amazon-rotation-services-prod \
		--profile sincerelyhers-prod \
		--role-arn arn:aws:iam::$$PROD_ACCOUNT_ID:role/DeploymentRole \
		--region us-east-2 \
		--parameter-overrides Environment=prod AppShortName=services SecretsPrefix=sp-api/sincerely-services BaseStackName=sincerelyhers-base-prod \
		--capabilities CAPABILITY_NAMED_IAM \
		--s3-bucket sincerelyhers-deploy-artifacts-prod \
		--s3-prefix rotation-services
